export enum EventType {
  click = 'click',
  rightClick = 'rightclick',
  dblClick = 'dblclick',
  drag = 'drag',
  dragEnd = 'dragend',
  mouseMove = 'mousemove',
  mouseOver = 'mouseover',
  mouseOut = 'mouseout',
  mouseDown = 'mousedown',
  mouseUp = 'mouseup',
  projectionChanged = 'projection_changed',
  zoomStart = 'zoomstart',
  zoomChanged = 'zoom_changed',
  zoomEnd = 'zoomend',
  headingChanged = 'heading_changed',
  idle = 'idle',
  tilesLoaded = 'tilesloaded',
  centerChanged = 'center_changed',
  boundsChanged = 'bounds_changed',
  radiusChanged = 'radius_changed',
  resize = 'resize',
  lineUpdate = 'lineupdate',
  mouseEnter = 'mouseenter',
  mouseLeave = 'mouseleave',
}
